### ISSUE TITLE
Can't generate the mock class for a protocol which has an associated type and a method with escaping closure

### ISSUE THREAD

**Issue by myihsan** [Brightify/Cuckoo#363] opened 2020-08-03 13:36 UTC
```swift
protocol SomeProtocol {
    associatedtype T
    func someMethod(closure: @escaping () -> Void)
}
```

The `DefaultImplCaller` generated by the protocol above is like below.

```swift
	 class DefaultImplCaller<T>: SomeProtocol {
	    private let reference: Any
	
	    
	    
	    init<_CUCKOO$$GENERIC: SomeProtocol>(from defaultImpl: UnsafeMutablePointer<_CUCKOO$$GENERIC>, keeping reference: @escaping @autoclosure () -> Any?) where _CUCKOO$$GENERIC.T == T {
	        self.reference = reference
	
	        
	        _storage$1$someMethod = defaultImpl.pointee.someMethod
	        
	    }
	    
	    
	
	    
	    private let _storage$1$someMethod: (() -> Void) -> Void
	     func someMethod(closure: @escaping () -> Void)  {
	        return _storage$1$someMethod(closure)
	    }
	    
	}
```

> Converting non-escaping value to '() -> Void' may allow it to escape

But `_storage$1$someMethod = defaultImpl.pointee.someMethod` causes this compiler error.

Is it possible to fix this issue without change the current implementation way of Cuckoo?

**Comment by MatyasKriz** [comment] 2020-08-03 19:47
Hey, @myihsan. I'm not sure just by hastily looking at this, might need some playing around to see if we can get it to work.

**Comment by ltk-arennow** [comment] 2023-09-20 19:17
Just as an FYI, this is still an ongoing issue. I'm sure it's not simple to solve, but it's a pretty significant roadblock if you run into it

**Comment by MatyasKriz** [comment] 2023-09-23 13:18
Hey, @ltk-arennow, so this problem only occurs for escaping closure parameters or does the associated type play a role as well?

**Comment by MatyasKriz** [comment] 2023-09-28 20:03
Looked into this in more detail and it seems like the type system will finally have to get cleaned up for this to be fixed. The issue is that the escaping attribute is not written into the type itself right now.

**Comment by ltk-arennow** [comment] 2023-09-28 20:21
I hate when an "I should deal with this some day" turns into a "this is now stopping me from doing something I want to". I appreciate you looking into it :)

**Comment by MatyasKriz** [comment] 2023-10-04 18:35
I've managed to get this working in Cuckoo 2.0, but I'm not ready to release it just yet.

**Comment by ltk-arennow** [comment] 2023-10-05 14:24
Glad to hear it. I'm always excited for a 2.0, and especially so in this case

**Comment by MatyasKriz** [comment] 2024-04-23 15:15
Sorry for the delay, I wasn't able to get any testers for the 2.0 PR, but I've decided to release it anyway after waiting for four months, so I'll close this as fixed. 🙂

**Closed by MatyasKriz** 2024-04-23 15:15 UTC
Labels: bug
