### ISSUE TITLE
Mocks/Stubs for class with arguments in initializer

### ISSUE THREAD

**Issue by ealymbaev** [Brightify/Cuckoo#216] opened 2018-08-13 05:01 UTC
I have a class that I want to be mocked (stubbed). But my class has initializer with arguments:

```
class MyClass(someArg: SomeArg) {
    self.someArg = someArg
}
```
And when I need to mock this class - it requires me to pass `someArg` to it. I want to mock the class itself and I don't want to care about how it is initialized.

Desired behaviour:
```
let mock = MockMyClass() // NOT! MockMyClass(someArg: ...)
```

I understand that mocking works via inheriting classes, so is there any workaround for this. It makes usage of Cuckoo framework very uncomfortable, especially when Dependency Injection is used widely.

**Comment by MatyasKriz** [comment] 2018-11-07 08:32
Duplicate of #207, if you have further questions, please ask for more information there.

**Closed by MatyasKriz** 2018-11-07 08:32 UTC
Labels: duplicate
