### ISSUE TITLE
"No stub found" error for function arguments

### ISSUE THREAD

**Issue by esen** [Brightify/Cuckoo#268] opened 2019-03-26 04:21 UTC
Hey,

I've encountered a problem with mocking methods which accept a function argument. 2 cases:

1. The following works: 

```swift
protocol SomeProtocol {
    func run(_ block: ((Bool) throws -> Void)) throws
}

class A {
    func doSmth(some: SomeProtocol) {
        some.run { boolValue in
             print("This works well")
        }
    }
}

// In tests

let mock = MockSomeProtocol()
stub(mock) { mock in
    when(mock.run(_: any())).then({ try? $0(true) })
}

a = A()
a.doSmth(mock)
```

2. If your function passed as argument has no arguments, then it doesn't work:

```swift
protocol SomeProtocol {
    func run(_ block: (() throws -> Void)) throws
}

class A {
    func doSmth(some: SomeProtocol) {
        some.run {
             print("This doesn't work")
        }
    }
}

// In tests

let mock = MockSomeProtocol()
stub(mock) { mock in
    when(mock.run(_: any())).then({ try? $0() })
}

a = A()
a.doSmth(mock)
```

This way, it cannot find the stub: 
```
No stub for method `run(_: (() throws -> Void)) throws` using parameters (Function).
```
Cuckoo version: 0.12.1

**Comment by MatyasKriz** [comment] 2019-03-26 05:49
Hey, please try using `feature/closureN` branch and let me know if this error still persists.

**Comment by esen** [comment] 2019-03-26 06:13
> Hey, please try using `feature/closureN` branch and let me know if this error still persists.

Unfortunately, the problem remains

**Comment by esen** [comment] 2019-03-26 06:17
It seems like in [MockManager.swift#43](https://github.com/Brightify/Cuckoo/blob/master/Source/MockManager.swift#L43) it can't downcast to 
`Cuckoo.ConcreteStub<() throws -> (), ()>`
while it can downcast for 
`Cuckoo.ConcreteStub<(Swift.Bool) throws -> (), ()>`
Strange ...

**Comment by MatyasKriz** [comment] 2019-03-27 11:15
Hey, the problem was on our end. Cuckoo didn't support closures without parameters or its support was very limited.

We have added the functionality for both throwing and non-throwing closures with up to 7 parameters.

@esen, please try to fetch Cuckoo again from the `feature/closureN` branch and test it out. Let me know how it went. Thanks for your issue!

**Comment by esen** [comment] 2019-03-28 08:35
> Hey, the problem was on our end. Cuckoo didn't support closures without parameters or its support was very limited.
> 
> We have added the functionality for both throwing and non-throwing closures with up to 7 parameters.
> 
> @esen, please try to fetch Cuckoo again from the `feature/closureN` branch and test it out. Let me know how it went. Thanks for your issue!

In GeneratedMocks.swift file my method with closure parameter says 
`Error:(2353, 38) use of unresolved identifier 'escapingStub'`
The generated mock method is:
```

func inTransaction(_ block: (() throws -> Void))  throws {
	return try withoutActuallyEscaping(block, do: { (block) in

    return try cuckoo_manager.callThrows("inTransaction(_: (() throws -> Void)) throws",
        parameters: (block),
        escapingParameters: (escapingStub(for: block)),
        superclassCall:
            
            Cuckoo.MockManager.crashOnProtocolSuperclassCall()
            ,
        defaultCall: __defaultImplStub!.inTransaction(block))
	})

}
```

and almost all of other method mocks say
`Error:(12420, 61) generic type '__DoNotUse' specialized with too few type parameters (got 1, but expected 2)`
The generated mock method is:
```
@discardableResult
func handle<M1: Cuckoo.Matchable>(getDataInventoryItem item: M1) -> Cuckoo.__DoNotUse<Bool> where M1.MatchedType == InventoryItem {
    let matchers: [Cuckoo.ParameterMatcher<(InventoryItem)>] = [wrap(matchable: item) { $0 }]
    return cuckoo_manager.verify("handle(getDataInventoryItem: InventoryItem) -> Bool", callMatcher: callMatcher, parameterMatchers: matchers, sourceLocation: sourceLocation)
}
```

**Comment by MatyasKriz** [comment] 2019-03-28 08:47
Hey, yeah, the problem is that your cuckoo generator is built from old source code, when calling the `run` script in your build phases, add the parameter `--clean` to build it again. You only need to run it with `--clean` once, then remove it when you reach a functional state.

**Comment by esen** [comment] 2019-03-28 12:03
> Hey, yeah, the problem is that your cuckoo generator is built from old source code, when calling the `run` script in your build phases, add the parameter `--clean` to build it again. You only need to run it with `--clean` once, then remove it when you reach a functional state.

`Error:(2389, 20) expression type '(_, (_) throws -> _) throws -> _' is ambiguous without more context`

For method 
```
func inTransaction(_ block: (() throws -> Void)) throws {
    return try withoutActuallyEscaping(block, do: { (block: @escaping (() throws -> Void)) in

        return try cuckoo_manager.callThrows("inTransaction(_: (() throws -> Void)) throws",
            parameters: (block),
            escapingParameters: ({ _ in fatalError("This is a stub! It's not supposed to be called!") }),
            superclassCall:
                
                Cuckoo.MockManager.crashOnProtocolSuperclassCall()
                ,
            defaultCall: __defaultImplStub!.inTransaction(block))
    })

}
```

Lots of `Error:(111, 128) ambiguous reference to member 'equal(to:)'`  and `Error:(178, 29) generic parameter 'T' could not be inferred` errors on possibly `any()` matchers. Before I didn't have these errors

**Comment by MatyasKriz** [comment] 2019-03-28 12:12
Okay, could you please provide the classes and methods from which some of the `any()` and `equal(to:)` errors occur along with the test code where these errors occur? We have tests, but they didn't catch this, so I want to add your test case and possibly fix the issue.

**Comment by TadeasKriz** [comment] 2019-03-28 12:15
@MatyasKriz I think it's because the `block` is wrapped in parentheses.
 Because of that, the `escapingParameters:` gets generated with a single `_` instead of `()`.

@esen Why do you have the parentheses around `() throws -> Void`?

**Comment by MatyasKriz** [comment] 2019-03-28 12:19
@TadeasKriz ah yes, that makes sense, will need to make the parser smarter.

**Comment by esen** [comment] 2019-03-29 04:03
> Okay, could you please provide the classes and methods from which some of the `any()` and `equal(to:)` errors occur along with the test code where these errors occur? We have tests, but they didn't catch this, so I want to add your test case and possibly fix the issue.

[Here](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/cf9c145897bcbd7494d123304245f80b6e358d1e/HSBitcoinKit/HSBitcoinKitTests/Blocks/BlockSyncerTests.swift#L271) is a `describe` scope I'm trying to make pass. There are plenty of other tests which may be useful too.

**Comment by esen** [comment] 2019-03-29 04:35
> @esen Why do you have the parentheses around `() throws -> Void`?

The same behavior without parentheses around

**Comment by MatyasKriz** [comment] 2019-05-14 17:06
Merged! I think this should be solved in the next release. Give it a try and if not, please reopen the issue.

**Closed by MatyasKriz** 2019-05-14 17:06 UTC
Labels: PR submitted
