### ISSUE TITLE
Generic parameter F could not be inferred when using factory method

### ISSUE THREAD

**Issue by ships** [Brightify/Cuckoo#305] opened 2019-08-11 02:13 UTC
Hi friends-

I am using factory method to do dependency injection with Foundation types, and therefore I have a type which I mock, in which there is a method which returns another type which I also mock:

```
protocol ProcessDouble {
    func run() throws
}

extension Process: ProcessDouble {}

protocol ProcessFactory {
    func makeProcess(cmd: String, args: [String]) -> ProcessDouble
}
```

Later, when I use this ProcessFactory, I get an error like seen in #212  and #176, which says `Generic parameter F could not be inferred` :

```
            let factory = MockProcessFactory()
            spy = MockProcessDouble()
            stub(factory) { stub in
                when(stub.makeProcess(cmd: "ls", args: ["-la"])).thenReturn(spy!)
            }
```

unlike the two aforementioned issues, there is no use of `Any` type in these methods, and there is not a property - just an ordinary method.

My intuition says that this may have something to do with the use of the protocol type as return value, being ambiguous like `Any`, but (a) there is no clear way to solve this problem because return value is not an arg, so there is no equivalent place to put the special `any()`, and (b) factory method is common enough in DI that I assume there is a normal way to do this.

What would that be? Or, what would you recommend? I am happy to specify the generic parameter but i am unsure which parameter and how.

Thank you!

**Comment by MatyasKriz** [comment] 2019-08-15 07:59
Hello, @ships.

Would you kindly fork Cuckoo, create a breaking test for this scenario that makes the generated code uncompilable, and create a PR? It will ease the burden off of me trying to reproduce it and make the fixing process faster. Furthermore, while you're at it and perhaps figure out why you're getting this problem, a fixing PR would be most precious to us.

Thanks in advance!

**Comment by ships** [comment] 2019-08-15 17:25
Hi @MatyasKriz , thanks yes I will get around to it when I can -- luckily I found a workaround but that means it will take me a little longer. But I really like this project and want to make sure if this is a bug and not just wrong usage, that I help to fix it.

**Comment by MatyasKriz** [comment] 2019-08-15 17:30
Thanks, that means a lot to us. 🙂 We'll be looking forward to your PR.

**Comment by MatyasKriz** [comment] 2019-09-04 14:02
Hey, @ships. I looked at your use-case and tried to reproduce the error you've encountered. The problem is that until now there were no convenience matchers for collections nor dictionaries, so passing the array like that doesn't work for the current version.

I will be adding these convenience matchers to make stubbing easier and more intuitive to use.

Meanwhile, you can use `equal(to: ["-la"])` as the matcher for the parameter `args` in this function.

As this is not really a bug, I'll be closing this issue. Happy mocking!

**Closed by MatyasKriz** 2019-09-04 14:02 UTC
