### ISSUE TITLE
Generator source fails to download without `--download` switch

### ISSUE THREAD

**Issue by pivotal-bolt** [Brightify/Cuckoo#280] opened 2019-05-15 17:29 UTC
When executing the `run` script for the first time, it properly detects that there is no generator, but if you do not pass the `--download <version>` switch, when it tries to download the generator source code you get the following output:

```
./run version
No Cuckoo Generator found.
~/workspace/Carthage/Checkouts/Cuckoo ~/workspace/Carthage/Checkouts/Cuckoo
./run: line 42: Generator: command not found
Couldn't build. Generator source code not found. (expected in the  directory)
Downloading version ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    454      0 --:--:-- --:--:-- --:--:--   455
curl: (3) <url> malformed
chmod: cuckoo_generator: No such file or directory
~/workspace/Carthage/Checkouts/Cuckoo
xargs: ./cuckoo_generator: No such file or directory
```

If you set the `--download <version>` switch, it works as expected:
```
./run version --download 1.0.1
No Cuckoo Generator found.
~/workspace/Carthage/Checkouts/Cuckoo ~/workspace/Carthage/Checkouts/Cuckoo
Downloading version 1.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3641  100  3641    0     0  14997      0 --:--:-- --:--:-- --:--:-- 14983
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0   2180      0 --:--:-- --:--:-- --:--:--  2187
100 13.0M  100 13.0M    0     0  1535k      0  0:00:08  0:00:08 --:--:-- 2015k
~/workspace/Carthage/Checkouts/Cuckoo

```

(The `version` command output is an empty string, but that's a different issue)

**Comment by MatyasKriz** [comment] 2019-05-16 07:23
Hey, the correct place of build options is before the command itself. It's `run --download [version] generate`. I know about the `version` command outputting nothing, but at the moment there are more pressing matters.

What I see here is that the `run` script can't find the `Generator` folder, it's outputted as "Couldn't build. Generator source code not found. (expected in the  directory)".

I'm not sure why Carthage wouldn't have the Generator folder available, but I'll take a look at this later.

It seems for now you'll have to download the generator instead of building it if you want to use Carthage. If you positively don't want to download the generator, try figuring this out yourself, a PR would be appreciated.

**Comment by MatyasKriz** [comment] 2019-05-16 11:06
I looked into it and it seems you found a bug, thank you for that.

I fixed the `run` script and now it should work as intended. It will be released in `1.0.2`.

**Comment by pivotal-bolt** [comment] 2019-05-16 21:19
Thanks for such a quick response, and for all your hard work on this framework :)

**Comment by MatyasKriz** [comment] 2019-05-17 09:14
Please let me know if the fixed `run` script works for you and if so, consider closing the issue.

If you're having any compile issues, try to force build/download by using the build option `--clean` before the `generate` command like so:
```
run --clean generate ...
```

**Comment by MatyasKriz** [comment] 2019-05-26 16:14
I'll be closing this issue for cleaning purposes, hopefully it's resolved for you.

If not, don't hesitate to reopen the issue or open a new one. Thanks again!

**Closed by MatyasKriz** 2019-05-26 16:14 UTC
Labels: bug

**Comment by jordanfallon-pivotal** [comment] 2019-05-26 16:16
Yes it is working perfectly, sorry I forgot to close it!
