### ISSUE TITLE
Missed methods for protocol with multiple inheritance

### ISSUE THREAD

**Issue by ned1988** [Brightify/Cuckoo#130] opened 2017-05-16 21:17 UTC
I have protocol: `BudgetPresenterDelegate` which is inherited from `BasePresenterDelegate`.
```
protocol BasePresenterDelegate: class {
    func showPage(title: String?)
    func showTabBar(title: String, image: UIImage, selected: UIImage)
    func showMessage(with title: String, _ message: String, _ actions: [UIAlertAction])
}
```

```
protocol BudgetPresenterDelegate: BasePresenterDelegate, CreateSearchTableViewHeaderDataSource {
    func cancelSearch()
    func showGroupList()
    func removeBottomOffset()
    func setBottomOffset(_ offset: Double)
    func refreshData(for mode: BudgetHeaderMode)
    func showCreateNewGroupMessage(message: NSAttributedString)
    func createBudgetCell(with title: String?) -> UITableViewCell?
}
```

In the generated file `MockBudgetDetailPresenterDelegate` I'll have next error:
```
Type 'MockBudgetDetailPresenterDelegate' does not conform to protocol 'BasePresenterDelegate'
```

**Comment by TadeasKriz** [comment] 2017-05-16 21:36
Hi, thanks for the report, does this happen with the latest version?

**Comment by ned1988** [comment] 2017-05-16 21:44
Yes, I'm using version `0.9.2`

P.S thanks for the quick response! :)

**Comment by TadeasKriz** [comment] 2017-05-16 22:16
Are both the protocol files set as inputs for the generator?

**Comment by ned1988** [comment] 2017-05-17 18:46
No, I understood later that it were different files and I didn't include them, but after I included all my classes to the script I have different errors:
```
/GeneratedMocks.swift:922:31: Value of optional type '()?' not unwrapped; did you mean to use '!' or '?'?
```

```
/GeneratedMocks.swift:1081:72: 'Category' is ambiguous for type lookup in this context
```
`Category` is a `CoreData` class

```
/GeneratedMocks.swift:3165:20: Method does not override any method from its superclass

**Comment by TadeasKriz** [comment] 2017-05-17 19:03
Please show me what's on those lines in `GeneratedMocks.swift`

**Comment by ned1988** [comment] 2017-05-17 21:22
One of the `/ShareBudgetTests/GeneratedMocks.swift:1108:59: 'Category' is ambiguous for type lookup in this context` errors:
```
override func category(for indexPath: IndexPath)  -> Category {
        
        return cuckoo_manager.call("category(for: IndexPath) -> Category",
            parameters: (indexPath),
            original: observed.map { o in
                return { (indexPath: IndexPath) -> Category in
                    o.category(for: indexPath)
                }
            })
        
    }
```

`/ShareBudget/ShareBudgetTests/GeneratedMocks.swift:1263:19: Property does not override any property from its superclass`
```
override var fetchedResultsController: NSFetchedResultsController<Category>! {
        get {
            return DefaultValueRegistry.defaultValue(for: (NSFetchedResultsController<Category>!).self)
        }
        
        set { }
        
    }
```

`/ShareBudget/ShareBudgetTests/GeneratedMocks.swift:934:31: Value of optional type '()?' not unwrapped; did you mean to use '!' or '?'?`
```
func willChangeContent()  {
        
        return cuckoo_manager.call("willChangeContent()",
            parameters: (),
            original: observed.map { o in
                return { () in
                    o.willChangeContent?()
                }
            })
        
    }
```

`XCode` suggestion is
```
func didChangeContent()  {
        
        return cuckoo_manager.call("didChangeContent()",
            parameters: (),
            original: observed.map { o in
                return { () in
                    o.didChangeContent?()
                }
            })!
        
    }
```

**Comment by TadeasKriz** [comment] 2017-05-17 21:50
This is quite interesting. The first two seems to be because of type ambiguity. Is it possible you have more than one `Category` type visible?

The third error is probably caused by the method being optional, which I might be able to fix easily.

**Comment by ned1988** [comment] 2017-05-18 06:19
I think I should have only type of `Category`. 

Maybe this can be a reason:
```
/ShareBudgetTests/GeneratedMocks.swift:1120:59: Found this candidate (ObjectiveC.Category)
/ShareBudget/ShareBudgetTests/GeneratedMocks.swift:1120:59: Found this candidate (ShareBudget.Category)
```

**Comment by TadeasKriz** [comment] 2017-05-18 11:17
Yes, that's the cause. What imports are in the `GeneratedMocks.swift` file? We probably need to implement this: https://github.com/Brightify/Cuckoo/issues/128 to fix your issue. However I don't know how at this moment.

**Comment by ned1988** [comment] 2017-05-18 17:46
```
import Cuckoo
@testable import ShareBudget

import CoreData
import UIKit
```

Yes seems like it is the same reason. I hope you'll found solution soon :)

**Comment by kurtguenther** [comment] 2017-06-28 03:03
I am running into the same issue where I have 
```
Foo.swift:
protocol Foo { 
  func controller(_ controller: ViewController, didMoveToFrame frame: Frame)
}
```
```
Bar.swift:
protocol Bar : Foo { }
```

For this to work, do I have to include both Foo.swift and Bar.swift, even though I just want Bar to be mocked?

**Comment by ned1988** [comment] 2017-06-28 07:39
If I'm not wrong it was my problem, I didn't include all files

**Comment by TadeasKriz** [comment] 2017-06-28 18:21
@kurtguenther Yes, both files are needed. We don't scan the whole project for Swift files as it might include something you don't want to be included as well as slow the generation (and compilation).

However, it would make sense to log a warning (or an error, but warning seems better) if the class/protocol inherits a type that's not set for the input. Of course we would probably have to add some wildcards like `UI*` and `NS*`, but it might work. What do you think about this? Also I'd like to know your opinion @ned1988.

Thanks!

**Comment by ned1988** [comment] 2017-06-30 07:28
@TadeasKriz do you mean to log a `warning` during compilation?
It is a nice idea to add wildcards but I think we can have some problems with `Swift`, because they are removing `NS` from class names (`Date` and etc).

**Comment by babakbo** [comment] 2018-09-25 23:37
We have a similar problem where we have

```
Foo.swift:
protocol Foo {
  func foo()
}
```
```
Bar.swift
protocol Bar : Foo { }
```
when I include both Foo.swift and Bar.swift, it generates class MockBar: Bar but does not add the method foo() so we get a compile error. Is this expected behavior?

**Comment by TadeasKriz** [comment] 2018-09-26 07:28
Hi @babakbo, if you included both Foo.swift and Bar.swift as inputs to the Cuckoo generator then it should result in `foo` being generated. If it's not, it has to be a bug. Would you mind looking into it and filing a pull request? Thanks!

**Comment by MatyasKriz** [comment] 2019-05-14 17:12
I'll be closing this issue for cleaning purposes.

**Closed by MatyasKriz** 2019-05-14 17:12 UTC
