### ISSUE TITLE
Error when running tests with Xcode 11 Beta

### ISSUE THREAD

**Issue by cltnschlosser** [Brightify/Cuckoo#306] opened 2019-08-20 15:53 UTC
This may be an xcode issue, but posting here.

```
(dlopen_preflight(*/Tests): Library not loaded: /usr/lib/swift/libswiftXCTest.dylib
  Referenced from: *Tests.xctest/Frameworks/Cuckoo.framework/Cuckoo
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftXCTest.dylib: mach-o, but not built for iOS simulator)
```

**Comment by cltnschlosser** [comment] 2019-08-20 17:14
Update: It was previously working on beta 5.

**Comment by cltnschlosser** [comment] 2019-08-29 02:46
Update: Still happening on Xcode11 Beta 7

**Comment by MatyasKriz** [comment] 2019-08-29 19:08
Hey, this issue occurs when you run Cuckoo tests or tests for your app? I'm asking to readily find the solution to this problem.

**Comment by cltnschlosser** [comment] 2019-08-29 21:41
Tests for my app. I found that if I statically link Cuckoo then the issue goes away. Seems to be an issue with importing XCTest from swift in a dynamic framework.

Maybe should file a radar.

**Comment by MatyasKriz** [comment] 2019-09-06 08:48
I just downloaded the Beta 7 and I'm not able to reproduce this on my dummy project where I test using Cuckoo as an app, not from just the tests.

Anyway, could you please reveal which package manager you're using? Also, using your package manager, please try to create a new project with just Cuckoo as its dependency and see if it crashes on you all the same.

This is a curious error and I hope it stays in Beta only.

**Comment by cltnschlosser** [comment] 2019-09-06 12:31
Cocoapods with use_frameworks! I’ve found it happens with all swift dynamic frameworks that import XCTest. iOSSnapshotTestCase has the same issue.

**Comment by MatyasKriz** [comment] 2019-09-06 12:35
Thanks for the update! It's a relief that it's not actually Cuckoo itself that's broken. Hopefully they fix this before Xcode 11 is released.

I'll close this issue for now. If this becomes a problem in Xcode 11, we'll reopen it and try to resolve it.

**Closed by MatyasKriz** 2019-09-06 12:35 UTC

**Comment by cagatayemekci** [comment] 2019-09-09 13:18
I'm using Carthage for package manager and I have taken the same error.

**Comment by cltnschlosser** [comment] 2019-09-11 19:17
Seems to be resolved with the latest xcode beta, are you still having issues @cagatayemekci ?

**Comment by halonsoluis** [comment] 2019-12-11 09:37
I'm seeing the same issue with Version 11.2.1 (11B500)
