### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by arkilis** [Brightify/Cuckoo#265] opened 2019-03-20 01:27 UTC
Code:

```swift
stub(ssProfileDataManagerMock) { (mock) in
    mock.getProfileData(anyClosure()).then { completion in
        completion("" as AnyObject, nil)
    }
}
```

`completion("" as AnyObject, nil)` always complaints about the error:

`Type of expression is ambiguous without more context`

Method declariton:

```swift
func getProfileData(_ completion: @escaping (_ result: AnyObject, _ error: NSError?) -> Void)
```

**Comment by MatyasKriz** [comment] 2019-03-20 03:33
Hey, your method takes in two parameters, so you need to pass two matchers.

**Comment by MatyasKriz** [comment] 2019-03-20 03:45
You should use the `when` function like so: `when(mock.getProfileData(anyClosure())).then...`. It reads better and even if right now the function only returns what it gets, that may change later to do some magic, so I recommend doing that now instead of having to rewrite it later.

**Comment by arkilis** [comment] 2019-03-20 04:03
I tried use the following as well:

```swift
stub(ssProfileDataManagerMock) { (mock) in
   when(mock.getProfileData(anyClosure())).then { completion in
        completion("" as AnyObject, nil)
    }
}
``` 
Still gives out the same error.

**Comment by TadeasKriz** [comment] 2019-03-20 07:01
@arkilis Please try:

```
stub(ssProfileDataManagerMock) { (mock) in
   when(mock.getProfileData(anyClosure())).then { completion in
        completion(("" as AnyObject, nil))
    }
}
```

with the extra parentheses in `completion`. I think this might be caused by generics. If so, we might need to look into it and add extra `anyClosure` methods to workaround this.

**Comment by arkilis** [comment] 2019-03-20 11:18
Still the same

![image](https://user-images.githubusercontent.com/1528028/54680450-9d027c80-4b55-11e9-825d-7f7f7038c129.png)

**Comment by MatyasKriz** [comment] 2019-03-20 11:34
Hey, the problem was that we did not support multiple closure parameters as far as I'm aware. The functionality has been implemented and can be found in the `feature/closureN` branch if you want to test it out!

Thanks for the report, @arkilis.

**Comment by arkilis** [comment] 2019-03-21 02:08
Thanks for your efforts on this. After tried with `feature/closureN`, there are some other errors:

```bash
dyld: lazy symbol binding failed: Symbol not found: _$S6Cuckoo10anyClosureAA16ParameterMatcherVyq0_x_q_tcGyr1_lF

dyld: Symbol not found: _$S6Cuckoo10anyClosureAA16ParameterMatcherVyq0_x_q_tcGyr1_lF
```

**Comment by TadeasKriz** [comment] 2019-03-21 07:04
This is a common thing we see with Xcode 10. Try cleaning your build path (Cmd+Shift+K should be the default keystroke) and then run the tests again.

**Comment by arkilis** [comment] 2019-03-22 22:18
Confirmed it is working!

Steps on solving this issue, maybe useful for others:

1. use feature/closureN
2. regenerate all the mock classes

If your project is still Swift 3, you can just use the `feature/closureN` commits.

regards,
Ben

**Comment by MatyasKriz** [comment] 2019-03-23 05:52
Hi, I'll keep this issue open before the PR is merged if that's fine by you. It could help others that are looking for a solution to the same problem before it's merged and released in the next version.

**Comment by MatyasKriz** [comment] 2019-05-14 17:05
Merged!

**Closed by MatyasKriz** 2019-05-14 17:05 UTC
Labels: PR submitted, enhancement
