### ISSUE TITLE
Stubs are not recognized for functions with closures

### ISSUE THREAD

**Issue by kudzaiTnexus** [Brightify/Cuckoo#275] opened 2019-05-07 03:07 UTC
I am trying to write a test for a simple class however cuckoo doesnt recognize one of my stubs which has a closure. Is there a way of stubbing a function with a closure.

The stub function is not being called , when i do a **po** on the interactor or delegate i can see that the tests are referencing the actual interactor or delegate and not the mocks.

My code :

    typealias SuccessBlock = (_ responseModel: [Weather]?) -> Void

    protocol WeatherInfo {
       func fetchCityWeather ( success: @escaping SuccessBlock,
                          failure: @escaping (_ error: NSError?) -> Void)
    }

    protocol WeatherUpdates: WeatherInfo {
       func fetchCityWeather ( success: @escaping SuccessBlock,
                          failure: @escaping (_ error: NSError?) -> Void)
    }

ViewMoodel :

    class WeatherViewModel {
    
          private var interactor: WeatherInteractor
          private weak var delegate: BaseViewModelDelegate?
    
          init(interactor: WeatherInteractor, delegate: BaseViewModelDelegate) {
            self.interactor = interactor
            self.delegate = delegate
          }
    
          func getUpdates() {
            interactor.fetchCityWeather( success: { [weak self] weather in
               // do something
            }) { (error) in
              // show error
        }
      }
    }

Test :

    class WeatherViewModelTests: XCTestCase {

    var classUnderTest: WeatherViewModel!
    let mockInteractor = MockWeatherInteractor()
    let mockDelegate = MockBaseViewModelDelegate()

     override func setUp() {
        classUnderTest = WeatherViewModel(interactor: mockInteractor,
                                          delegate: mockDelegate)
     }

    func testThatClosureReturnsCorrectValue() {
        var mockUpdates: [Weather]? = nil
        var testBool = false
        
        stub(mockInteractor) {
            when($0.fetchCityWeather( success: anyClosure(), failure: anyClosure())).then({ success, _ in
                testBool = true
                success(mockUpdates)
            })
        }
        
        classUnderTest.getUpdates()
        
        XCTAssertTrue(testBool)
      }

    }

**Comment by MatyasKriz** [comment] 2019-05-14 17:10
Hey, could you please try to reproduce this on the 1.0.0 version?

**Comment by rio258k** [comment] 2019-05-21 21:39
I am also having issues stubbing methods with closures.

**Comment by MatyasKriz** [comment] 2019-05-22 05:37
Hey, @rio258k, as you sure understand, just stating that something doesn't work for you gives me no clues as to where to look to resolve your issue.

Ideally state the Cuckoo version you're using, show us the code that's being mocked and finally the way you're trying to stub it.

**Comment by MatyasKriz** [comment] 2019-05-28 10:29
I just tried this with the `1.0.5` version and couldn't reproduce it. I'll close this issue for cleaning purposes. If you can reproduce it, please file a PR with failing tests using your scenario. That will also help us evade this problem in the future.

**Closed by MatyasKriz** 2019-05-28 10:29 UTC
