### ISSUE TITLE
Generated code not properly formatted

### ISSUE THREAD

**Issue by imGurpreetSK** [Brightify/Cuckoo#250] opened 2018-12-07 05:28 UTC
The code generated by the library is not formatted properly. A lot of extra new lines are present in the code. Example snippet attached along-with:

```
class MockRequestable: Requestable, Cuckoo.ProtocolMock {
    typealias MocksType = Requestable
    typealias Stubbing = __StubbingProxy_Requestable
    typealias Verification = __VerificationProxy_Requestable
    let cuckoo_manager = Cuckoo.MockManager(hasParent: false)

    

    

    

	struct __StubbingProxy_Requestable: Cuckoo.StubbingProxy {
	    private let cuckoo_manager: Cuckoo.MockManager
	
	    init(manager: Cuckoo.MockManager) {
	        self.cuckoo_manager = manager
	    }
	    
	    
	}

	struct __VerificationProxy_Requestable: Cuckoo.VerificationProxy {
	    private let cuckoo_manager: Cuckoo.MockManager
	    private let callMatcher: Cuckoo.CallMatcher
	    private let sourceLocation: Cuckoo.SourceLocation
	
	    init(manager: Cuckoo.MockManager, callMatcher: Cuckoo.CallMatcher, sourceLocation: Cuckoo.SourceLocation) {
	        self.cuckoo_manager = manager
	        self.callMatcher = callMatcher
	        self.sourceLocation = sourceLocation
	    }
	
	    
	
	    
	}

}

 class RequestableStub: Requestable {
    

    

    
}


class MockApi: Api, Cuckoo.ClassMock {
    typealias MocksType = Api
    typealias Stubbing = __StubbingProxy_Api
    typealias Verification = __VerificationProxy_Api
    let cuckoo_manager = Cuckoo.MockManager(hasParent: true)

    

    

    
    // ["name": "v1Url", "returnSignature": " -> String", "fullyQualifiedName": "v1Url(from: String) -> String", "parameterSignature": "from path: String", "parameterSignatureWithoutNames": "path: String", "inputTypes": "String", "isThrowing": false, "isInit": false, "isOverriding": true, "hasClosureParams": false, "@type": "ClassMethod", "accessibility": "", "parameterNames": "path", "call": "from: path", "parameters": [CuckooGeneratorFramework.MethodParameter(label: Optional("from"), name: "path", type: "String", range: CountableRange(2984..<3001), nameRange: CountableRange(2984..<2988))], "returnType": "String", "isOptional": false, "stubFunction": "Cuckoo.ClassStubFunction"]
     override func v1Url(from path: String)  -> String {
        
            return cuckoo_manager.call("v1Url(from: String) -> String",
                parameters: (path),
                superclassCall:
                    
                    super.v1Url(from: path)
                    )
        
    }
    
```

**Comment by TadeasKriz** [comment] 2018-12-07 08:43
Hi, thank you for the report. The amount of whitespaces is caused by our use of Stencil and how it handles new lines in its statements. Although it might be nice to have a clean output, it doesn't contribute to the feature-set of Cuckoo and I'd consider it a low priority task.

This would be a good started-issue for someone that's looking to contribute to Cuckoo.

**Comment by MatyasKriz** [comment] 2024-04-27 10:33
This has been greatly improved in Cuckoo 2.0. I'll close this for now, but I welcome any PR that pushes the generated code beauty even further.

**Closed by MatyasKriz** 2024-04-27 10:33 UTC
Labels: enhancement, good first issue
