### ISSUE TITLE
Value of type Stubbing has no member...

### ISSUE THREAD

**Issue by zcsipler** [Brightify/Cuckoo#164] opened 2018-01-26 13:38 UTC
I am trying to use Cuckoo with Carthage submodules but it is not working. GeneratedMock are generated correctly I think, but it does not recognize any method on the mock when I try  stubbing. 

```
public protocol InteractorInputProtocol: class {
    weak var presenter: InteractorOutputProtocol! { get set }

    func fetchData()
}

public protocol InteractorOutputProtocol: class {
}
```

My test file:

```
class ExampleTests: XCTestCase {
    private var mockInteractor: MockInteractorInputProtocol!
    private var sut: Presenter!

    override func setUp() {
        super.setUp()

        mockInteractor = MockInteractorInputProtocol()

        sut = Presenter(interactor: mockInteractor)
    }
    override func tearDown() {
        super.tearDown()
    }

    func test_viewDidLoad() {
        stub(mockInteractor) { stub in
            when(stub.fetchData()).thenDoNothing(_)
        }
        sut.viewDidLoad()
    }
}
```

As long as I see I did everything as it is written in documentation but still I got build error with message: 

 "Value of type 'Stubbing' has no member 'fetchData' "

You can reproduce the issue on my test project available under this url:

https://github.com/zcsipler/ExampleProject.git

To run carthage I use 

carthage update --use-submodules --no-build

**Comment by TadeasKriz** [comment] 2018-01-26 13:57
Hi, I tried the project and I can see what's wrong.

On this line: `when(stub.fetchData()).thenDoNothing(_)` you need to remove the underscore. So the corrected line looks like this: `when(stub.fetchData()).thenDoNothing()`. Then it'll work as expected.

The compiler can get confused and display a wrong error, since we use generics heavily in Cuckoo. Unfortunately this is not something we could fix itself.

**Comment by zcsipler** [comment] 2018-01-26 15:13
Hi, thanks for you answer! Indeed, if I remove the "_" sign it works in the example project, but in our main project in that case the compiler forces me to put it there otherwise I get "Missung argument for parameter #1 in call" compiler error:

![screen shot 2018-01-26 at 16 10 44](https://user-images.githubusercontent.com/19905641/35445958-920ad462-02b3-11e8-9861-5f1eeb745e18.png)

This is weird because it is some swift 4 related thing as I know but both my example project and the main project uses swift 4 and it works in one and doesn't work in the other. I will try to figure out what would cause this difference but if you have any idea please share it. 

Thanks!

**Comment by TadeasKriz** [comment] 2018-01-26 15:15
Could you show me the `fetchFacebookUserInfo` function signature?

**Comment by zcsipler** [comment] 2018-01-26 16:11
Ok, the problem with stubbing fetchFacebookUserInfo was that it was in a protocol extension and it seems in this case the function it is not placed in the generated mock file. But it's fine because I want to stub the protocol anyway. However, the same issue appears when I try to stub setting a variable. 

In the presenter's constructor I set interactor's presenter:

```
 init(interactor: InteractorInputProtocol) {
        self.interactor = interactor

        self.interactor.presenter = self
    }
```

So when I initialize presenter in the test, I want to stub setting presenter property on the mockInteractor and then I get this result:

![screen shot 2018-01-26 at 17 07 21](https://user-images.githubusercontent.com/19905641/35448727-692762b0-02bb-11e8-85cc-e60487692e25.png)

So sorry for the confusion but this is the original issue that led me to add the "_" character. I also updated the example project on githb where you can reproduce this issue:

https://github.com/zcsipler/ExampleProject.git

**Comment by TadeasKriz** [comment] 2018-01-26 16:42
Unfortunately extensions cannot be overriden so we can't create Mock for them.

The error you are now seeing is caused by `sut` (`Presenter`) not being `Matchable`. 

Cuckoo needs to know how to distinguish parameters from each other and it uses `Matchable` for that. There are many builtin matchers, but I think they won't work with protocols.

You can add the following function to your code:
```
func match(_ value: InteractorOutputProtocol) -> ParameterMatcher<InteractorOutputProtocol?> {
    return equal(to: value, equalWhen: { $0 === $1 })
}
```
and then use it like so:
```
stub(mockInteractor) { stub in
    when(stub.presenter.set(match(sut))).thenDoNothing()
}
```

or you can just use the `equal` like so:
```
stub(mockInteractor) { stub in
    when(stub.presenter.set(equal(to: sut, equalWhen: { $0 === $1 }))).thenDoNothing()
}
```

**Comment by zcsipler** [comment] 2018-01-26 17:05
If I use the match func you suggested the test crashed with EXC_BAD_INSTRUCTION:

<img width="924" alt="screen shot 2018-01-26 at 18 03 38" src="https://user-images.githubusercontent.com/19905641/35451384-4e4618ee-02c3-11e8-8424-f1bbf4f98f0c.png">

Your second suggestion is not compiling either:

<img width="989" alt="screen shot 2018-01-26 at 18 04 58" src="https://user-images.githubusercontent.com/19905641/35451418-76735a16-02c3-11e8-95ef-ff397212c174.png">

**Comment by TadeasKriz** [comment] 2018-01-26 17:15
You're right, the second doesn't work because it's ambiguous, nothing to do about that. But the first one works on my end. What does the `EXC_BAD_INSTRUCTION` says?

This is how it looks on my machine:
![image](https://user-images.githubusercontent.com/284197/35451832-d47d68f8-02c4-11e8-8778-54a747848166.png)

**Comment by zcsipler** [comment] 2018-01-30 11:05
Hi, sorry for the delay. So in my case I put the stub first and then I init the sut, because mockInteractor's presenter is set when we call the constructor to initialize sut. In my understanding you first have to stub and then call the method where the stubbed setter is called, or do I misunderstand something? If I use it in your order (first Presenter call constructor and then stub the setter) it will not crash but I will get the following error when I initialize sut in setUp:

"No stub for method `presenter#set` using parameters Optional(Example.Presenter) and no original implementation was provided."

My thought was that it is reasonable because I stub too late and I have to do it before initializing the presenter. Is it correct? If you change the order of this two lines (first stub setter and then call presenter constructor) I think you will be able to reproduce the crash but I inserted some screenshot where is it coming from:
<img width="270" alt="screen shot 2018-01-30 at 11 51 31" src="https://user-images.githubusercontent.com/19905641/35562974-7ae2fc2e-05b5-11e8-9c87-afb5a533b60d.png">
<img width="994" alt="screen shot 2018-01-30 at 11 51 43" src="https://user-images.githubusercontent.com/19905641/35562983-825c8402-05b5-11e8-8a0a-76451154f75b.png">

**Comment by TadeasKriz** [comment] 2018-01-30 11:58
I see now. Well, you're trying to create a cyclic dependency and that's not possible. You can replace the `match(sut)` with `any()` to allow anything into the stub. Then it won't crash.

The EXC_BAD_INSTRUCTION is thrown because the `sut` is nil when the stubbing is created. It's even nil when it's being first used.

You are trying to match against something that doesn't exist yet.

**Comment by zcsipler** [comment] 2018-01-30 12:09
Ok I see, you are right! I will just use any() then to make to init work. Thanks for your help!

**Comment by zcsipler** [comment] 2018-01-30 17:33
I am sorry for come up with this again but I ran into similar problem when I am trying to stub calling/getting blocks of the mocked class. So the first question, is it even possible to stub/verify calling a block? Let's say there is a block defined in the protocol that is mocked:

`var onLoginSuccess: (() -> Void)? { get set }`

And I call this in a method I am writing the test for:

```
func handleLoginSuccess() {
        router.onLoginSuccess?()
    }
```

So if I write test for handleLoginSuccess I want to stub onLoginSuccess getter and verify is the block is called. I try to stub calling the get on block liket this:

```
func test_handleLoginSuccess() {
        // Arrange
        stub(mockRouter) { mockRouter in
            when(mockRouter.onLoginSuccess.get).thenDoNothing()
        }

        // Act
        sut.handleLoginSuccess()
    }
```

And then the compiler forces me again to put the "-" sign in the last clousre otherwise I get this "missing argument for parameter #1" error. Or can it be the problem that the block is optional?

**Comment by TadeasKriz** [comment] 2018-01-30 17:46
I'm not 100% sure, but I think you need to return something from the `get`. So you would have to do: `when(mockRouter.onLoginSuccess.get).thenReturn(nil)` (or `.thenReturn({ })`). Try it and let me know.

**Comment by zcsipler** [comment] 2018-01-30 19:17
Yes you were right I need to return something and it works to stub the getter. Also I figured out I could verifying calling the block in this way:

```
func test_handleLoginSuccess() {
        // Arrange
        var onLoginSuccessBlockCalled = false
        let onLoginSuccessBlock = {
            onLoginSuccessBlockCalled = true
        }
        
        stub(mockRouter) { mockRouter in
            when(mockRouter.onLoginSuccess.get).thenReturn(onLoginSuccessBlock)
        }

        // Act
        sut.handleLoginSuccess()

        // Assert
        XCTAssertTrue(onLoginSuccessBlockCalled)
    }
```

If you have better suggestion let me know :)

**Comment by zcsipler** [comment] 2018-01-31 13:13
There is an other issue came up with mocking blocks: what if I have a parameter in the block?
For instance:

`var onError: ((String) -> Void) { get }`

So I call the block on interactor:

```
func viewDidLoad() {
        interactor.fetchData()
        interactor.onError("Error")
    }
```

And I try to stub the block getter as before:

```
stub(mockInteractor) { stub in
            when(stub.onError.get).thenReturn(onErrorBlockBlock)
        }
```

It ends up again " Value of type '_.Stubbing' has no member 'onError' " 
I also updated the example project on github to be able to reproduce it.

**Comment by MatyasKriz** [comment] 2019-01-30 16:02
Hey @zcsipler, I just tried this in 0.12.0 with this protocol:
```
public protocol InteractorInputProtocol {
    var onError: (String) -> Void { get }
}
```
and with this test case:
```
func test_viewDidLoad() {
    let mockInteractor = MockInteractorInputProtocol()
    let onErrorBlockBlock: (String) -> Void = { name in
        print("Hello, \(name).")
    }
    stub(mockInteractor) { stub in
        when(stub.onError.get).thenReturn(onErrorBlockBlock)
    }

    mockInteractor.onError("World")
    mockInteractor.onError("zcsipler")
}
```
And it prints out
`Hello, World.`,
`Hello, zcsipler.`
respectively.

That makes me believe that somewhere along the way, your issue has been fixed. I'll close it for now. If you still get these errors on 0.12.0 or later, please reopen this issue or open a new one if it's not remotely connected to this issue.

**Closed by MatyasKriz** 2019-01-30 16:02 UTC
