### ISSUE TITLE
Run script to generate mocks always takes a long time to execute after upgrade to Cuckoo 0.12.0

### ISSUE THREAD

**Issue by aleksanderk** [Brightify/Cuckoo#227] opened 2018-10-19 10:20 UTC
After upgrading Cuckoo to 0.12.0 the `Run script` to generate mocks is taking a long time to execute. Even when there are no changes in the code the `Run script` always takes the same (long) time to execute as on the first/clean run.

**Comment by MatyasKriz** [comment] 2018-10-19 10:41
Hey there, could you please provide the `Run script` you are using? Thanks!

**Comment by aleksanderk** [comment] 2018-10-19 12:10
We are using Xcode 9.4.1.
Our script looks like this:

```
# Define output file. Change "$PROJECT_DIR/Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="$PROJECT_DIR/ProjectTests/Cuckoo/GeneratedMocks.swift"
echo "Generated Mocks File = $OUTPUT_FILE"

# Define input directory. Change "$PROJECT_DIR" to your project's root source folder, if it's not the default name.
INPUT_DIR="$PROJECT_DIR/ProjectV3/"
echo "Mocks Input Directory = $INPUT_DIR"

# Generate mock files, include as many input files as you'd like to create mocks for.
Carthage/Checkouts/Cuckoo/run generate --testable "Project_3" --no-timestamp \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/Protocols/Protocol1.swift" \
"$INPUT_DIR/Protocols/Protocol2.swift" \
"$INPUT_DIR/Protocols/Protocol3.swift" \

# ... and so forth

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.
```

**Comment by TadeasKriz** [comment] 2018-10-19 12:13
Thank you. Could you also provide the output of this script from Xcode?

**Comment by aleksanderk** [comment] 2018-10-19 13:17
Output of the script can be seen here: https://gist.github.com/aleksanderk/68448c97712471cd79f8144f691323ee

**Comment by aleksanderk** [comment] 2018-10-25 09:28
Hey guys, do you have any clues why the script would always take so long to run? We have the same issue also with Xcode 10.

**Comment by MatyasKriz** [comment] 2018-11-09 15:21
I've tried reproducing this issue by creating a new project with Carthage, but can't seem to find the reason it takes you a long time. It's nearly instantaneous for me, granted I don't have many classes, so the issue is somehow particular to your code. Maybe you found an edge case that causes Cuckoo to perform a lot of computations.

I understand that your code may be private, however it would greatly help me in finding the bug and fixing it. If you can provide me with something that may not be in usual code and might be causing it, please let me know!

**Comment by nfgrilo** [comment] 2018-11-12 11:59
Hey @MatyasKriz !

I'm a @aleksanderk colleague, so sharing the same project and script mentioned earlier. 
I sampled the process while it was taking all the CPU, so maybe this could help!

<img width="815" alt="screen shot 2018-11-12 at 11 52 39" src="https://user-images.githubusercontent.com/2744944/48346029-acd2f700-e671-11e8-95e2-fafb084bc411.png">

[Sample of cuckoo_generator 1.txt](https://github.com/Brightify/Cuckoo/files/2571793/Sample.of.cuckoo_generator.1.txt)
[Sample of cuckoo_generator 2.txt](https://github.com/Brightify/Cuckoo/files/2571794/Sample.of.cuckoo_generator.2.txt)
[Sample of cuckoo_generator 3.txt](https://github.com/Brightify/Cuckoo/files/2571795/Sample.of.cuckoo_generator.3.txt)

As an additional note (maybe that's expected), the process started with memory usage below 10MB and finished with > 400 MB.
The whole process takes around ~ 1 min on my Macbook Pro 15".

Hope this helps,
Nuno

**Comment by MatyasKriz** [comment] 2018-12-10 12:05
I'm sorry, I've been going through the logs, but I don't think I can salvage any useful information that way. You can either try tracking down the problem yourself or try to pinpoint the file that is causing the problems and share it with us to test.

I don't think the problem is with too many files, as you listed only 3 protocols to mock.

If it's not a single file and something is not right in the generator, we can talk further.

**Comment by MatyasKriz** [comment] 2019-03-20 16:09
I can't reproduce this and will close this issue for now. If someone can pinpoint the problem and provide a minimal example that takes significantly longer to generate, I'd gladly fix this, but right now, without almost any leads, it's like looking for a needle in a haystack.

**Closed by MatyasKriz** 2019-03-20 16:09 UTC
