### ISSUE TITLE
Error when creating function Mocks with generics

### ISSUE THREAD

**Issue by JJaviMS** [Brightify/Cuckoo#347] opened 2020-06-22 11:04 UTC
Hello, I´m using Cuckoo for my test and I found a problem when you are generating the Stubs for functions that use generics.

Let´s assume the following class

```
class GenericWrapper<A> {
    
}
```

And then the following class for our generic function:
```
class GenericFunc {
    
    func functionWithGenerics<U, Gen:GenericWrapper<U>>(arg: Gen) -> String {
        return "ABC"
    }
}
```

The problem comes when the function mock is created, the generated header is the following:
`override func functionWithGenerics<U, Gen: GenericWrapper<U>>>(arg: Gen) -> String `

As you can see the generic argument puts an extra '>' so the code doesn´t compile.

**Comment by MatyasKriz** [comment] 2020-06-22 11:11
Hey, @JJaviMS. Thanks for the report, I'll take a look at it when I find the time. If you poke around Cuckoo source code and find the issue yourself, I'd greatly appreciate it.

I think you can sidestep this problem for now by moving the `: GenericWrapper<U>` part to the `where` clause of the function instead.

**Comment by JJaviMS** [comment] 2020-06-23 06:48
Hi, @MatyasKriz. I have tryed the `where` workaround, but it still have problems, the generated code doesn´t contains the generic between the '<>' characters.

 The new function declaration is `func functionWithGenerics<U, Gen> (arg: Gen) -> String where Gen:GenericWrapper<U>` and the generated code is `override func functionWithGenerics<U, Gen>(arg: Gen) -> String where Gen:GenericWrapperU`.

I´ve been looking into the code and I think the problem could be in `Generator.swift` into the function `matchableGenericTypes`. If I finally find the bug I will try to solve it.

**Comment by MatyasKriz** [comment] 2020-06-23 06:53
Hmm, try to put a space after the colon, so it's `Gen: GenericWrapper<U>`, that might be the cause of the bug.

**Comment by JJaviMS** [comment] 2020-06-23 07:04
It keeps failing, ` func functionWithGenerics<U, Gen> (arg: Gen) -> String where Gen: GenericWrapper <U>` generates `override func functionWithGenerics<U, Gen>(arg: Gen) -> String where Gen: GenericWrapper U`. It seems that in the `where` clause it ignores the `<>`characters

**Comment by MatyasKriz** [comment] 2020-06-23 07:06
Looking at the tests, this case of generics within generics is missing, so it's certainly possible that we missed this and you're the first one to report it.

**Comment by JJaviMS** [comment] 2020-06-23 07:15
I think those are two differents bugs, I mean one is the double '>' and the other the `where` without the '<>'. After following an execution I have found the problem for the double '>' could be in the `Tokenizer.tokenize` method, because the generic arrives with the double '>'.

`["key.name": "Gen", "key.offset": 198, "key.elements": [["key.kind": "source.lang.swift.structure.elem.typeref", "key.offset": 202, "key.length": 18]], "key.nameoffset": 198, "key.length": 22, "key.inheritedtypes": [["key.name": "GenericWrapper<U>>"]], "key.namelength": 3, "key.kind": "source.lang.swift.decl.generic_type_param"]
`

**Comment by MatyasKriz** [comment] 2020-06-23 07:18
Yes, I agree. I should've added more extensive tests for this kind of complicated feature.

Regarding the double `>>`, that seems as an off-by-one error.

**Comment by JJaviMS** [comment] 2020-06-23 07:24
I followed an execution trace and the problem comes when the Tokens are generated, in the method Tokenizer class in the tokenize method the value `structure` already have the error, and this class comes from the library SourceKitten so maybe the error is out of the scope of this project

**Comment by MatyasKriz** [comment] 2020-06-28 14:30
Hey, @JJaviMS. It turns out that I completely forgot to add these cases into the tests. They weren't functional at all until now. I want to thank you for bringing this into the light.

What I found out is this:
- `SourceKitten` has an off-by-one bug, that's the case when the generic inheritance is specified before the function parameters
- `Cuckoo` had a bug that neglected to include any form of nesting character in the final type. I can't believe I overlooked this.

I've fixed the `where` inheritance not including the characters.

However the `SourceKitten` bug can be sidestepped even in your current version by adding a space in front of the last `>`, so your generics would look like `<U, Gen: GenericWrapper<U> >`. I know it's ugly, so I've included a temporary fix for this use-case in Cuckoo, so that `<U, Gen: GenericWrapper<U>>` excludes the last `>`. I'll be reporting this issue to `SourceKitten` and hopefully get it fixed there as well.

Thanks again for reporting this bug! I'll release the fix as soon as I can, hopefully today. Let me know if your generated code is compilable now and see you around. 🙂

**Comment by JJaviMS** [comment] 2020-07-07 11:59
Hi  @MatyasKriz 

I have tried the workaround and its working!

Thanks for the help!

Should we keep the issue open until `SourceKitten` fix the problem?

**Comment by MatyasKriz** [comment] 2020-07-07 12:13
I'm glad you're able to sidestep this for now, @JJaviMS.

If you have the time, I'd greatly appreciate it if you could test the `fix/generics` branch where both use cases should be fixed on our end. Simply use the `--clean` argument when running the `run` script.

Leaving the issue open for now is probably a good idea in case anyone else wonders why more complex generic inheritance seems to fail. I'd probably close it after releasing the fix in the `fix/generics` branch.

**Comment by JJaviMS** [comment] 2020-07-07 12:28
I tried the `fix/generics` branch and it seems to work properly with the code that was giving me problems. 👍

**Comment by MatyasKriz** [comment] 2020-07-07 12:29
That's great to hear. I'll release a patch today, then.

**Comment by MatyasKriz** [comment] 2020-07-08 08:25
The fixes are in `master` and will be released shortly.

Thanks again for reporting this and have a nice day!

**Closed by MatyasKriz** 2020-07-08 08:25 UTC
Labels: PR submitted, bug
